function(create_theme_target THEME_TARGET THEME_GEN_TARGET)
    set(THEME_DIR "${CMAKE_SOURCE_DIR}/resources/themes")
    set(THEME_DIST "${CMAKE_BINARY_DIR}/themegen")
    file(MAKE_DIRECTORY "${THEME_DIST}")

    file(GLOB RES_THEME_FILES RELATIVE "${THEME_DIR}" CONFIGURE_DEPENDS "${THEME_DIR}/*.css")

    set(_theme_files)
    foreach(_file ${RES_THEME_FILES})
        string(REGEX REPLACE css$ c2theme _gen_file "${_file}")
        set(_gen_path "${THEME_DIST}/${_gen_file}")

        add_custom_command(
            OUTPUT 
                ${_gen_path}
            COMMAND
                cstylegen 
                    theme 
                        -o "${THEME_DIST}"
                        ${_file}
            WORKING_DIRECTORY
                "${CMAKE_SOURCE_DIR}/resources/themes"
            COMMENT
                "Generating ${_file}"
            DEPENDS
                "${CMAKE_SOURCE_DIR}/resources/themes/${_file}"
        )
        list(APPEND _theme_files ${_gen_path})
        list(APPEND THEME_QRC_FILES "    <file>${_gen_file}</file>")
    endforeach()

    list(JOIN THEME_QRC_FILES "\n" THEME_QRC_FILES)
    configure_file(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/themes_autogenerated.qrc.in ${THEME_DIST}/themes_autogenerated.qrc @ONLY)

    add_custom_target(${THEME_TARGET} DEPENDS ${_theme_files})

    set(DEFAULT_STYLE Dark.css)

    add_custom_command(
        OUTPUT
            "${CMAKE_BINARY_DIR}/autogen/GeneratedTheme.timestamp"
        BYPRODUCTS
            "${CMAKE_BINARY_DIR}/autogen/GeneratedTheme.cpp"
            "${CMAKE_BINARY_DIR}/autogen/GeneratedTheme.hpp"
        COMMAND
            cstylegen
                code
                    -o "${CMAKE_BINARY_DIR}/autogen"
                    -t
                    ${DEFAULT_STYLE}
        WORKING_DIRECTORY
            "${CMAKE_SOURCE_DIR}/resources/themes"
        COMMENT
            "Generating GeneratedTheme.{cpp,hpp,timestamp}"
        DEPENDS
            "${CMAKE_SOURCE_DIR}/resources/themes/layout.yml"
    )

    add_custom_target(${THEME_GEN_TARGET} DEPENDS "${CMAKE_BINARY_DIR}/autogen/GeneratedTheme.timestamp")

    set(GEN_THEME_FILES 
            "${THEME_DIST}/themes_autogenerated.qrc"
            "${CMAKE_BINARY_DIR}/autogen/GeneratedTheme.cpp"
            "${CMAKE_BINARY_DIR}/autogen/GeneratedTheme.hpp"
        PARENT_SCOPE
    )
endfunction()
