---
name: clang-tidy

on:
  pull_request:

concurrency:
  group: clang-tidy-${{ github.ref }}
  cancel-in-progress: true

env:
  CHATTERINO_REQUIRE_CLEAN_GIT: On
  C2_BUILD_WITH_QT6: Off

jobs:
  clang-tidy:
    name: "clang-tidy ${{ matrix.os }}, Qt ${{ matrix.qt-version }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Ubuntu 22.04, Qt 6.6
          - os: ubuntu-22.04
            qt-version: 6.6.2
            plugins: true

      fail-fast: false

    steps:
      - name: Enable plugin support
        if: matrix.plugins
        run: |
          echo "C2_PLUGINS=ON" >> "$GITHUB_ENV"
        shell: bash

      - name: Set BUILD_WITH_QT6
        if: startsWith(matrix.qt-version, '6.')
        run: |
          echo "C2_BUILD_WITH_QT6=ON" >> "$GITHUB_ENV"
        shell: bash

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # allows for tags access

      - name: Install Qt6
        if: startsWith(matrix.qt-version, '6.')
        uses: jurplel/install-qt-action@v3.3.0
        with:
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache-${{ matrix.qt-version }}-v2
          modules: qt5compat qtimageformats
          version: ${{ matrix.qt-version }}
          dir: ${{ github.workspace }}/.qtinstall

      - name: clang-tidy review
        timeout-minutes: 20
        uses: ZedThree/clang-tidy-review@v0.18.0
        with:
          build_dir: build-clang-tidy
          config_file: ".clang-tidy"
          split_workflow: true
          exclude: "lib/*,tools/crash-handler/*"
          cmake_command: >-
            ./.CI/SetupClangTidyCMake.sh ${{matrix.qt-version}}
          apt_packages: >-
            libsecret-1-dev,
            libboost-dev, libboost-system-dev, libboost-filesystem-dev,
            libssl-dev,
            rapidjson-dev,
            libbenchmark-dev

      - name: clang-tidy-review upload
        uses: ZedThree/clang-tidy-review/upload@v0.18.0
