---
name: Test Ubuntu

on:
  pull_request:
  workflow_dispatch:
  merge_group:

env:
  TWITCH_PUBSUB_SERVER_TAG: v1.0.7
  QT_QPA_PLATFORM: minimal

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "${{ matrix.os }}"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-22.04"
            container: ghcr.io/chatterino/chatterino2-build-ubuntu-22.04:latest
            qt-version: 6.6.1
            plugins: true
      fail-fast: false
    env:
      C2_PLUGINS: ${{ matrix.plugins }}
      C2_BUILD_WITH_QT6: ${{ startsWith(matrix.qt-version, '6.') }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create build directory (Ubuntu)
        run: mkdir build-test

      - name: Install googlebench
        run: |
          sudo apt update
          sudo apt -y install \
            libbenchmark-dev

      - name: Install LLVM and Clang
        uses: gentoo-root/install-llvm-action@abb6cec0ec431e834bc5e5090ea39a2d1d63a4c6
        with:
          version: 18

      - name: Build (Ubuntu)
        run: |
          cmake \
            -DBUILD_TESTS=On \
            -DBUILD_BENCHMARKS=On \
            -DBUILD_APP=OFF \
            -DCHATTERINO_PLUGINS="$C2_PLUGINS" \
            -DCMAKE_PREFIX_PATH="$Qt6_DIR/lib/cmake" \
            -DBUILD_WITH_QT6="$C2_BUILD_WITH_QT6" \
            -DCHATTERINO_STATIC_QT_BUILD=On \
            -DCMAKE_CXX_FLAGS="-fprofile-instr-generate -fcoverage-mapping" \
            -DCMAKE_C_FLAGS="-fprofile-instr-generate -fcoverage-mapping" \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_COMPILER=clang \
            ..
          cmake --build .
        working-directory: build-test

      - name: Download and extract Twitch PubSub Server Test
        run: |
          mkdir pubsub-server-test
          curl -L -o pubsub-server.tar.gz "https://github.com/Chatterino/twitch-pubsub-server-test/releases/download/${{ env.TWITCH_PUBSUB_SERVER_TAG }}/server-${{ env.TWITCH_PUBSUB_SERVER_TAG }}-linux-amd64.tar.gz"
          tar -xzf pubsub-server.tar.gz -C pubsub-server-test
          rm pubsub-server.tar.gz
          cd pubsub-server-test
          curl -L -o server.crt "https://github.com/Chatterino/twitch-pubsub-server-test/raw/${{ env.TWITCH_PUBSUB_SERVER_TAG }}/cmd/server/server.crt"
          curl -L -o server.key "https://github.com/Chatterino/twitch-pubsub-server-test/raw/${{ env.TWITCH_PUBSUB_SERVER_TAG }}/cmd/server/server.key"
          cd ..

      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo Install httpbox
        run: |
          cargo install --git https://github.com/kevinastone/httpbox --rev 89b971f

      - name: Test
        timeout-minutes: 30
        run: |
          httpbox --port 9051 &
          cd ../pubsub-server-test
          ./server 127.0.0.1:9050 &
          cd ../build-test
          export LLVM_PROFILE_FILE="cov/c2-%p.profraw"
          ctest --repeat until-pass:4 --output-on-failure --exclude-regex ClassicEmoteNameFiltering
        working-directory: build-test

      - name: Export Coverage
        run: |
          llvm-profdata merge -sparse cov/c2-*.profraw -o default.profdata
          llvm-cov export bin/chatterino-test --instr-profile default.profdata --format lcov lcov.txt
        working-directory: build-test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          file: build-test/lcov.txt
          token: ${{ secrets.CODECOV_TOKEN }}
